[build]
#target = "thumbv6m-none-eabi"

[env]
SDK_PATH = "/opt/DA145xx_SDK/6.0.22.1401"

[target.thumbv6m-none-eabi]
rustflags = [ "-C", "linker=arm-none-eabi-gcc" ]
runner = "arm-none-eabi-gdb -x jlink.gdb"

[profile.release]
opt-level = "z"
lto = true
debug = true # does not impact final binary
