name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: podman pull shiftcrypto/da14531

      - run: >
        podman run
          --volume ${{github.workspace}}:/checkout
          --workdir /checkout
          --env CARGO_TERM_COLOR
          --env RUSTFLAGS
          shiftcrypto/da14531
          .ci/ci
