name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: make dockerpull

      - run: docker run -e CARGO_TERM_COLOR=${CARGO_TERM_COLOR} -e RUSTFLAGS=${RUSTFLAGS} shifcrypto/da14531 .ci/c
