name: CI
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  # Enable "Deny warnings" when all warnings are cleared
  #RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - run: podman pull shiftcrypto/da14531

      - run: >
          podman run
          --volume ${{github.workspace}}:/checkout
          --workdir /checkout
          --env CARGO_TERM_COLOR
          shiftcrypto/da14531
          .ci/ci
